### ISSUE TITLE
能用dev模式不？

### ISSUE THREAD

**Issue by morelearn1990** [z-z-k/vite-plugin-amd-babel#1]
@z-z-k 大兄弟，还在吗？ie9的兼容想找你探讨一下，能用dev模式不？

**Comment by morelearn1990** [comment]
这个包没有发在npm上呀？

**Comment by z-z-k** [comment]
可以,我在公司的几个项目中使用过,不过是直接写到项目里面的,这个代码没有维护

**Comment by z-z-k** [comment]
我最新的是用esl.js来加载,比require体积更小,加入urlArgs来防止缓存

**Comment by z-z-k** [comment]
加入 babelHelpers: "runtime",可以转译更多语法,但是体积会大一些

**Comment by z-z-k** [comment]
`const cheerio = require('cheerio');
const { babel } = require('@rollup/plugin-babel');
const buildtime = Date.now()
function amd(options) {
    if (!options) options = {};
    var esl = options.esl || "/js/esl.js";
    return {
        name: 'bohe-compatible',
        apply: 'build',
        configResolved(resolvedConfig) {
            resolvedConfig.plugins.push(babel({
                extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue']
            }))
        },
        config(config, { command }) {
            if (command === 'build') {
                var build = config.build;
                if (!build) {
                    build = config.build = {};
                }
                var rollupOptions = build.rollupOptions;
                if (!rollupOptions) {
                    rollupOptions = build.rollupOptions = {};
                }
                var output = rollupOptions.output;
                if (!output) {
                    output = rollupOptions.output = {};
                }
                build.polyfillModulePreload = false;
                output.format = "amd";
                output.freeze = options.freeze || false;
                output.strict = options.strict || false;
                output.interop = options.interop || false;
            }
        },

        transformIndexHtml(html, ctx) {
            const $ = cheerio.load(html);
            var entries = [];
            $('script[type=module]').each(function () {
                var url = $(this).attr('src');
                if (!url.match(/^\w+:/.test(url))) {
                    entries.push(url);
                    $(this).remove();
                }
            });
            $('link[rel=modulepreload]').each(function () {
                var url = $(this).attr('href');
                if (!url.match(/^\w+:/.test(url))) {
                    entries.push(url);
                    $(this).remove();
                }
            });
            $('link[rel=stylesheet]').each(function () {
                var url = $(this).attr('href');
                if (!url.match(/^\w+:/.test(url))) {
                    if (url == '/css/style.css') {
                        $(this).attr('href', `${url}?t=${buildtime}`)
                    }
                }
            });
            $('body').append(
                $('<script></script>').attr('src', esl)
            );
            let main = /^(.+)\.js$/.exec(entries[0])[1]
            $('body').append(
                $(`<script>require.config({ urlArgs: "t=${buildtime}" });require(["${main}"])</script>
`)
            );
            return $.html();
        }
    }
}
export default amd()`

**Comment by z-z-k** [comment]
我整理了一个最新代码demo发你的邮箱了
https://t.wss.ink/f/8m4gyyztm3x

**Comment by morelearn1990** [comment]
感谢大佬。
前端的发展一骑绝尘，但是对于老旧浏览器抛弃的态度，导致我们这些还在工作在旧浏览器环境的人完全没法适应，就好像被遗忘在世界之端(｡ ́︿ ̀｡)

**Comment by morelearn1990** [comment]
我看代码，只在打包模式下生效哦？我尝试一下在 dev 模式下能不能成功，我这儿经常需要在低版本浏览器上进行调试开发，如果每次打包后才能在低版本浏览器上浏览的话，我这儿就会比较麻烦，调试起来就不怎么顺畅了。

**Comment by z-z-k** [comment]
> 我看代码，只在打包模式下生效哦？我尝试一下在 dev 模式下能不能成功，我这儿经常需要在低版本浏览器上进行调试开发，如果每次打包后才能在低版本浏览器上浏览的话，我这儿就会比较麻烦，调试起来就不怎么顺畅了。

去掉apply: 'build'试试, 开发还是要点体验的,如果开发阶段还走babel那还不如用webpack

**Comment by morelearn1990** [comment]
不得行，esl会报错
```
Uncaught Error: [REQUIRE_FATAL]Relative ID is not allowed in global require: ./index/index
    at r (esl.js:1:204)
    at （索引）:35:90
```

**Comment by morelearn1990** [comment]
我使用requireJs代替，就会换成另外的错误
```
Uncaught TypeError: Failed to resolve module specifier "@babel/runtime/helpers/toConsumableArray". Relative references must start with either "/", "./", or "../".


index.js?t=1655890559487:1 Uncaught SyntaxError: Cannot use import statement outside a module (at index.js?t=1655890559487:1:1)
```

**Comment by z-z-k** [comment]
> 我使用requireJs代替，就会换成另外的错误
> 
> ```
> Uncaught TypeError: Failed to resolve module specifier "@babel/runtime/helpers/toConsumableArray". Relative references must start with either "/", "./", or "../".
> 
> 
> index.js?t=1655890559487:1 Uncaught SyntaxError: Cannot use import statement outside a module (at index.js?t=1655890559487:1:1)
> ```

在25行,我漏了一个
`if (command === 'build' || true) {`

**Comment by morelearn1990** [comment]
开发模式不能用，于是试了一下打包，存在错误：
```
[vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
    at onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
    at Object.onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:23226:13)
    at ModuleLoader.handleResolveId (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22510:26)
    at /Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22471:26
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by morelearn1990** [comment]
如果将command === "build" 打开，会提示
```
Uncaught SyntaxError: Cannot use import statement outside a module (at index.js?t=1655891310384:1:1)
```
这是由于这个 index 文件不是 require 格式的代码，没有做过 amd 格式的转换

**Comment by z-z-k** [comment]
> 开发模式不能用，于是试了一下打包，存在错误：
> 
> ```
> [vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> error during build:
> Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
>     at onRollupWarning (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
>     at onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
>     at Object.onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:23226:13)
>     at ModuleLoader.handleResolveId (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22510:26)
>     at /Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22471:26
>  ELIFECYCLE  Command failed with exit code 1.
> ```

看样子不行,vite运行的时候是esm的,formats只是打包的时候转换。看样子只能在打包的时候用,  
还有一种方法是用rollup+esbuild 我配一个给你

**Comment by morelearn1990** [comment]
↖(^ω^)↗ 感谢大佬

**Comment by z-z-k** [comment]
> > 开发模式不能用，于是试了一下打包，存在错误：
> > ```
> > [vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
> > This is most likely unintended because it can break your application at runtime.
> > If you do want to externalize this module explicitly add it to
> > `build.rollupOptions.external`
> > error during build:
> > Error: [vite]: Rollup failed to resolve import "@babel/runtime/helpers/defineProperty" from "src/utils/api.js".
> > This is most likely unintended because it can break your application at runtime.
> > If you do want to externalize this module explicitly add it to
> > `build.rollupOptions.external`
> >     at onRollupWarning (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
> >     at onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/vite@2.9.12_less@4.1.3/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
> >     at Object.onwarn (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:23226:13)
> >     at ModuleLoader.handleResolveId (/Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22510:26)
> >     at /Users/morelearn/Desktop/vite_vue2_amd_demo/node_modules/.pnpm/rollup@2.75.7/node_modules/rollup/dist/shared/rollup.js:22471:26
> >  ELIFECYCLE  Command failed with exit code 1.
> > ```
> 
> 看样子不行,vite运行的时候是esm的,formats只是打包的时候转换。看样子只能在打包的时候用, 还有一种方法是用rollup+esbuild 我配一个给你
我之前配过一个,去掉了一点东西,rollup+esbuild速度比vite还快,但是感觉热更新弱一点
https://t.wss.ink/f/8mettsv4xjr

**Comment by morelearn1990** [comment]
感谢～^_^
